<?xml version="1.0" encoding="utf-8"?><Database Name="Anusuchak" Class="SchedulerTasksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=Anusuchak;Integrated Security=True" SettingsObjectName="EmailScheduler.Properties.Settings" SettingsPropertyName="AnusuchakConnectionString" Provider="System.Data.SqlClient" />
</Database>